### ISSUE TITLE
install flashlight-cuda[asr] failed

### ISSUE THREAD

**Issue by indifferen** [facebookresearch/flashlight#386]
[178/183] : && /usr/bin/c++ -fPIC -g  CMakeFiles/fl_asr_decode.dir/flashlight/app/asr/Decode.cpp.o -o bin/asr/fl_asr_decode -L/opt/intel/mkl/lib/intel64   -L/usr/local/cuda/targets/x86_64-linux/lib/stubs   -L/usr/local/cuda/targets/x86_64-linux/lib -Wl,-rpath,/opt/intel/mkl/lib/intel64:/home/xx/vcpkg/packages/arrayfire_x64-linux/lib:/home/xx/vcpkg/installed/x64-linux/debug/lib:/home/xx/vcpkg/installed/x64-linux/lib:  libflashlight-app-asr.a  -ldl  /home/xx/vcpkg/installed/x64-linux/lib/libgflags.a  libflashlight.a  libfl-libraries.a  -lmkl_gf_lp64  -lmkl_sequential  -lmkl_core  -lm  /home/xx/vcpkg/installed/x64-linux/debug/lib/libfftw3.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libkenlm.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libkenlm_util.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libbz2d.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/xx/vcpkg/packages/arrayfire_x64-linux/lib/libafcuda.so.3.7.3  -pthread  /home/xx/vcpkg/installed/x64-linux/lib/libcudnn.so  /home/xx/vcpkg/installed/x64-linux/debug/lib/libmpi.so  /home/xx/vcpkg/installed/x64-linux/lib/libnccl.so  /usr/local/cuda/lib64/libcudart_static.a  -ldl  -lpthread  /usr/lib/x86_64-linux-gnu/librt.so  /home/xx/vcpkg/installed/x64-linux/debug/lib/libsndfile.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libvorbisenc.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libvorbis.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libFLAC.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libogg.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libopus.a  -lm  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl && :
FAILED: bin/asr/fl_asr_decode 
: && /usr/bin/c++ -fPIC -g  CMakeFiles/fl_asr_decode.dir/flashlight/app/asr/Decode.cpp.o -o bin/asr/fl_asr_decode -L/opt/intel/mkl/lib/intel64   -L/usr/local/cuda/targets/x86_64-linux/lib/stubs   -L/usr/local/cuda/targets/x86_64-linux/lib -Wl,-rpath,/opt/intel/mkl/lib/intel64:/home/xx/vcpkg/packages/arrayfire_x64-linux/lib:/home/xx/vcpkg/installed/x64-linux/debug/lib:/home/xx/vcpkg/installed/x64-linux/lib:  libflashlight-app-asr.a  -ldl  /home/xx/vcpkg/installed/x64-linux/lib/libgflags.a  libflashlight.a  libfl-libraries.a  -lmkl_gf_lp64  -lmkl_sequential  -lmkl_core  -lm  /home/xx/vcpkg/installed/x64-linux/debug/lib/libfftw3.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libkenlm.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libkenlm_util.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libbz2d.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/xx/vcpkg/packages/arrayfire_x64-linux/lib/libafcuda.so.3.7.3  -pthread  /home/xx/vcpkg/installed/x64-linux/lib/libcudnn.so  /home/xx/vcpkg/installed/x64-linux/debug/lib/libmpi.so  /home/xx/vcpkg/installed/x64-linux/lib/libnccl.so  /usr/local/cuda/lib64/libcudart_static.a  -ldl  -lpthread  /usr/lib/x86_64-linux-gnu/librt.so  /home/xx/vcpkg/installed/x64-linux/debug/lib/libsndfile.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libvorbisenc.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libvorbis.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libFLAC.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libogg.a  /home/xx/vcpkg/installed/x64-linux/debug/lib/libopus.a  -lm  -lcudadevrt  -lcudart_static  -lrt  -lpthread  -ldl && :
/usr/bin/ld: warning: libcudart.so.10.1, needed by /home/xx/vcpkg/installed/x64-linux/lib/libnccl.so, not found (try using -rpath or -rpath-link)
libflashlight-app-asr.a(ctc_entrypoint.cu.o): In function `CpuCTC<float>::CpuCTC(int, int, void*, int, int)':
/home/xx/vcpkg/buildtrees/flashlight-cuda/src/4bc14022f7-7b8557c63e.clean/flashlight/app/asr/third_party/warpctc/include/detail/cpu_ctc.h:28: undefined reference to `omp_set_num_threads'
/home/xx/vcpkg/buildtrees/flashlight-cuda/src/4bc14022f7-7b8557c63e.clean/flashlight/app/asr/third_party/warpctc/include/detail/cpu_ctc.h:30: undefined reference to `omp_get_max_threads'
libfl-libraries.a(PowerSpectrum.cpp.o): In function `fl::lib::audio::PowerSpectrum::batchApply(std::vector<float, std::allocator<float> > const&, int)':
/home/xx/vcpkg/buildtrees/flashlight-cuda/src/4bc14022f7-7b8557c63e.clean/flashlight/lib/audio/feature/PowerSpectrum.cpp:101: undefined reference to `GOMP_parallel'
libfl-libraries.a(PowerSpectrum.cpp.o): In function `fl::lib::audio::PowerSpectrum::batchApply(std::vector<float, std::allocator<float> > const&, int) [clone ._omp_fn.0]':
/home/xx/vcpkg/buildtrees/flashlight-cuda/src/4bc14022f7-7b8557c63e.clean/flashlight/lib/audio/feature/PowerSpectrum.cpp:102: undefined reference to `omp_get_num_threads'
/home/xx/vcpkg/buildtrees/flashlight-cuda/src/4bc14022f7-7b8557c63e.clean/flashlight/lib/audio/feature/PowerSpectrum.cpp:102: undefined reference to `omp_get_thread_num'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaGetDeviceCount@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaIpcCloseMemHandle@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `__cudaRegisterFunction@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaGetErrorString@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaIpcOpenMemHandle@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaMemcpyAsync@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaHostAlloc@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaEventCreateWithFlags@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaMemset@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `__cudaRegisterVar@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaStreamSynchronize@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaSetDevice@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaFreeHost@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaIpcGetMemHandle@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `__cudaRegisterFatBinaryEnd@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaMemcpy@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaHostGetDevicePointer@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaStreamCreateWithFlags@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaPointerGetAttributes@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaStreamWaitEvent@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaHostUnregister@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaDeviceGetPCIBusId@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaGetDevice@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `__cudaPopCallConfiguration@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaFree@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaEventDestroy@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaLaunchKernel@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaDeviceCanAccessPeer@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaLaunchCooperativeKernelMultiDevice@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaDeviceGetAttribute@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaStreamDestroy@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `__cudaUnregisterFatBinary@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaDeviceEnablePeerAccess@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaMalloc@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaHostRegister@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaGetLastError@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `__cudaRegisterFatBinary@libcudart.so.10.1'
/home/xx/vcpkg/installed/x64-linux/lib/libnccl.so: undefined reference to `cudaEventRecord@libcudart.so.10.1'
collect2: error: ld returned 1 exit status

ubuntu18.04
cmake version 3.10.2
g++ (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0

**Comment by jacobkahn** [comment]
@indifferen — the problem here is that you're using a NCCL version that is compiled to work with CUDA 10.0 (the one that comes with `vcpkg`), but you have CUDA 10.1, so the linking is failing.

You should `vcpkg remove nccl` and `vcpkg remove cudnn` if you've installed it and install NCCL and cuDNN from [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html) and [here](https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html), respectively. **You will need to install versions of each that work with CUDA 10.1**, since that's the CUDA version you have installed.

After that, you can try installing `flashlight-cuda[asr]` again.

https://github.com/microsoft/vcpkg/pull/15379 should also fix the other linker issue you're having. That should be merged in the next day - after that you can re-pull your vcpkg repo and try again.

I'll keep this open - let me know if you're still having issues.

**Comment by jacobkahn** [comment]
@indifferen did the build succeed?

**Comment by indifferen** [comment]
> @indifferen did the build succeed?

yes，tannk you！
