### ISSUE TITLE
Cuda sources (CriterionUtils.cu,...) compilation failure

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#270]
### Bug Description
Cuda sources (CriterionUtils.cu,...) compilation failure

#### Reproduction Steps
- git pull the very master as today specially the upgrade to cmake 3.10 f5f84c464e63db83ed1bc876c968791bc9c5b20d
- cmake with 3.12+
- make

### Platform and Hardware
ubuntu 16, cuda 10.2

#### Additional Context
```
[ 12%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/usr/local/cuda/bin/nvcc  -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DKENLM_MAX_ORDER=6 -I/home/wtambellini/repos/flashlight -I/usr/include/openblas -I/home/wtambellini/repos/kenlm -I/home/wtambellini/repos/flashlight/release/CUB/src/CUB -I/usr/local/cuda/include   -x cu -c /home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/Defines.h(14): warning: scoped enumeration types are a C++11 feature
/home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu(24): error: explicit type is missing ("int" assumed)
```
As you can see the std=c++11 is not set in the nvcc CLI.
It's because the cmake team has changed their mind several times about how to handle cuda.
Todays FL master is setting a global var in CUDAUtils.cmake: 
```
function (set_cuda_cxx_compile_flags)
  set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS};-std=c++11" PARENT_SCOPE)
  # Using host flags makes things bad - keep things clean
  set(CUDA_PROPAGATE_HOST_FLAGS OFF)
endfunction()
```
which does nt work anymore with 'recent' cmake.
 
The proper way to do is said to set target props:  adding 
```
  target_compile_options(fl-libraries PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--std=c++11>)
```
seems to fix the error.

Refs:
https://forums.developer.nvidia.com/t/passing-flags-to-nvcc-via-cmake/75768/2

**Comment by tlikhomanenko** [comment]
cc @jacobkahn could you add this fix in cmake or @WilliamTambellini feel free to send PR?

**Comment by zjuturtle** [comment]
I cannot build for cmake 3.19.1. Context below

```
[build] make[3]: *** [third/flashlight/CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o] Error 1
[build] nvcc fatal   : redefinition of argument 'std'
```

Delete `--std=c++11` seems solve[Ref](https://github.com/facebookresearch/DetectAndTrack/issues/57)

**Comment by jacobkahn** [comment]
@WilliamTambellini this is what I was talking about :)

**Comment by WilliamTambellini** [comment]
Hum, I ve just tried and seems to build correctly with todays master and cmake 3.19:
```
[ 20%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o
/usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DKENLM_MAX_ORDER=6 -I/home/wtambellini/repos/flashlight -I/usr/include/openblas -I/home/wtambellini/repos/kenlm -I/home/wtambellini/repos/flashlight/release/CUB/src/CUB -I/usr/local/cuda/include -O3 -DNDEBUG --std=c++14 -Xcompiler -pthread -std=c++14 -x cu -c /home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o
```
The c++14 flag appears twice but nvcc (10.2) does not seem to care. Perhaps depends on the version of nvcc though.
Status with todays master:
- CUDAUtils.cmake does set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS};-std=c++11" PARENT_SCOPE)
- fl lib cmakelists sets target_compile_options(fl-libraries PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--std=c++14>)

@jacobkahn I see at least these options:
1- I could simply remove the  target_compile_options(fl-libraries PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--std=c++14>) : only usefull for recent cmake, using cmake 3.10 just simpler. Supporting wide range of cmake versions in FL is anyway quite time consuming and perhaps not that worth it (at least for my usecase).
2- switching to target_compile_options(fl-libraries PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--std=c++11>), not 14. Safer.
3- I could retouch the CUDAUtils.cmake to upgrade to std to c++14 (not 11): could be usefull in the near futur but worry about old cuda (9 ?) support. 
Your call,
W.

**Comment by jacobkahn** [comment]
@WilliamTambellini I actually think the `CUDA_NVCC_FLAGS` approach should work fine — I've just found what I think it is the issue: [this line](https://github.com/facebookresearch/flashlight/blob/5b0771abdbcf1f39037b3a7d322faebfd4eca43b/cmake/CUDAUtils.cmake#L23) was never changed! Testing now with a few different versions of CMake.

**Comment by WilliamTambellini** [comment]
@jacobkahn apparently the issue was not because of 2 std c++ flags but indeed because of 2 conflictual std=c++ (11 and 14) in the same command line. Good to see you ve upgraded cuda compilation to std 14.

Though, master does nt compile anymore for me even with cmake 3.10 : 
...
[  6%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/usr/local/cuda/bin/nvcc  -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DKENLM_MAX_ORDER=6 -I/home/wtambellini/repos/flashlight -I/usr/include/openblas -I/home/wtambellini/repos/kenlm -isystem=/usr/include -I/home/wtambellini/repos/flashlight/release/CUB/src/CUB -I/usr/local/cuda/include  -O3 -DNDEBUG   -x cu -c /home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/Defines.h(14): warning: scoped enumeration types are a C++11 feature
/home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu(24): error: explicit type is missing ("int" assumed)
...

I ve added a message after the set:
  set_cuda_cxx_compile_flags()
  message(STATUS "CUDA_NVCC_FLAGS=${CUDA_NVCC_FLAGS}")
and I see that 
CUDA_NVCC_FLAGS=;-std=c++14 
at cmake init, but is probably reset/cleared later on as it does not appear in the final nvcc commandline.

Hum, I see that I m using cmake 3.10.0 vs 3.10.2 on ubuntu18. ReRe upgrading ...

**Comment by WilliamTambellini** [comment]
@jacobkahn  apparently CUDA_NVCC_FLAGS does not seem to do anything anymore even in the FL circle CI jobs: 
from
https://app.circleci.com/pipelines/github/facebookresearch/flashlight/755/workflows/c784063f-fe74-40f6-a963-273aeab68f41/jobs/1544/steps

see that there is no std c++ flag but (for some reasons) nvcc (10.0 ?) does not complain:

[ 16%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/usr/local/cuda/bin/nvcc  -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DFL_LIBRARIES_USE_MKL -DKENLM_MAX_ORDER=6 -I/flashlight -I/opt/intel/mkl/include -I/root/kenlm -I/flashlight/build/CUB/src/CUB -I/usr/local/cuda/include   -x cu -c /flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
[ 16%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o
/usr/local/cuda/bin/nvcc  -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DFL_LIBRARIES_USE_MKL -DKENLM_MAX_ORDER=6 -I/flashlight -I/opt/intel/mkl/include -I/root/kenlm -I/flashlight/build/CUB/src/CUB -I/usr/local/cuda/include   -x cu -c /flashlight/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o

On my side I cannot downgrade to cuda10.0 so as today I cannot compile FL master without
 target_compile_options(fl-libraries PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--std=c++14>)
Kind
W.

**Comment by jacobkahn** [comment]
@WilliamTambellini aha. That's some good investigation. Let's add that `target_compile_options` stuff back and kill everything related to `CUDA_NVCC_FLAGS`.

Seems like `nvcc` guesses or infers the C++ std to compile with pretty randomly... not great :). I'll send a fix.

**Comment by WilliamTambellini** [comment]
Cool, tks. I guess/hope nvidia has good reasons to rely on the host compiler but for FL/AF, it s indeed safer to hard set the std in the cmake, not randomly relying on the local gcc. CU.

**Comment by jacobkahn** [comment]
@WilliamTambellini I have a fix - turns out 
```
set(CMAKE_CUDA_STANDARD 14)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)
```
Is the right way to go. Tested with a bunch of CMake versions. Will send the commit shortly.

**Comment by WilliamTambellini** [comment]
Hi @jacobkahn 
I ve just repulled/rebased and it sadly still fails :) because no std cpp in the nvcc line:
```
/usr/local/cuda/bin/nvcc  -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DKENLM_MAX_ORDER=6 -I/home/wtambellini/repos/flashlight -I/usr/include/openblas -I/home/wtambellini/repos/kenlm -I/home/wtambellini/repos/flashlight/release/CUB/src/CUB -I/usr/local/cuda/include  -O3 -DNDEBUG   -x cu -c /home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/Defines.h(14): warning: scoped enumeration types are a C++11 feature
```

But good news, I know why : seen in the cmake doc:
https://cmake.org/cmake/help/v3.10/prop_tgt/CUDA_STANDARD.html#prop_tgt:CUDA_STANDARD
set_property(TARGET tgt PROPERTY CUDA_STANDARD 11)
"This property is initialized by the value of the CMAKE_CUDA_STANDARD variable if it is set when a target is created."

In the fl lib CMakeLists, you create the lib
add_library(  fl-libraries  
and then later (too late)
  set(CMAKE_CUDA_STANDARD 14)
  set(CMAKE_CUDA_STANDARD_REQUIRED ON)

I ve set these global vars at the top of the cmake file (before creating the target), and then it does work:
[ 17%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
/usr/local/cuda/bin/nvcc  -DFL_LIBRARIES_USE_CUDA -DFL_LIBRARIES_USE_KENLM -DKENLM_MAX_ORDER=6 -I/home/wtambellini/repos/flashlight -I/usr/include/openblas -I/home/wtambellini/repos/kenlm -I/home/wtambellini/repos/flashlight/release/CUB/src/CUB -I/usr/local/cuda/include  -O3 -DNDEBUG   -std=c++14 -x cu -c /home/wtambellini/repos/flashlight/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu -o CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o

Conclusion: we just have to move these global var sets earlier. Would you like me to ?

**Comment by jacobkahn** [comment]
@WilliamTambellini I have a commit right now doing this. Another good catch though! WE should do this before we do we do anything else at the configuration stage of the fl build.
